app = "apifold-web"
primary_region = "ams"

[build]
  dockerfile = "../../apps/web/Dockerfile"
  [build.args]
    NEXT_PUBLIC_APP_URL = "https://apifold.dev"
    NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY = "pk_live_Y2xlcmsuYXBpZm9sZC5kZXYk"
    NEXT_PUBLIC_POSTHOG_KEY = "phc_fh9thxLJgBGkTWrrZVwLkNAIUXmo4E6xLO2Zkr9XpVH"
    NEXT_PUBLIC_POSTHOG_HOST = "https://eu.i.posthog.com"
    NEXT_PUBLIC_RUNTIME_URL = "https://apifold-runtime.fly.dev"

[env]
  NODE_ENV = "production"
  PORT = "3000"

[http_service]
  internal_port = 3000
  force_https = true
  auto_start_machines = true
  auto_stop_machines = true
  min_machines_running = 1

[[vm]]
  size = "shared-cpu-1x"
  memory = "512mb"
